// src/lib/components/shell/Sidebar.svelte
<script>
	import { page } from '$app/state';
	import { crossfade, fade } from 'svelte/transition';
	import { cubicOut } from 'svelte/easing';
	import { PanelLeftClose, PanelLeftOpen } from 'lucide-svelte';
	import Logo from './Logo.svelte';
	import { visibleNavigation } from '$lib/navigation';

	/**
	 * @type {{
	 *   profile: any,
	 *   collapsed?: boolean,
	 *   mobile?: boolean,
	 *   onnavigate?: () => void
	 * }}
	 */
	let { profile, collapsed = $bindable(false), mobile = false, onnavigate } = $props();

	const groups = $derived(visibleNavigation(profile));

	// Indicateur actif qui « glisse » d'une entrée à l'autre
	const [send, receive] = crossfade({ duration: 220, easing: cubicOut });

	/** @param {string} href */
	function isActive(href) {
		const path = page.url.pathname;
		if (href === '/deplacements') return path === href; // l'historique a sa propre entrée
		if (href === '/admin') return path === '/admin' || path.startsWith('/admin/utilisateur');
		return path === href || path.startsWith(`${href}/`);
	}

	const compact = $derived(collapsed && !mobile);
</script>

<nav
	aria-label="Navigation principale"
	class="flex h-full flex-col border-r border-line bg-surface/70 backdrop-blur-xl"
	style:width={mobile ? '100%' : compact ? 'var(--sidebar-w-collapsed)' : 'var(--sidebar-w)'}
	style:transition="width var(--d-slow) var(--ease-out)"
>
	<div
		class="flex h-[var(--topbar-h)] shrink-0 items-center px-4 {compact
			? 'justify-center px-0'
			: ''}"
	>
		<a href="/accueil" class="rounded-md" onclick={onnavigate} aria-label="CSM — tableau de bord">
			<Logo withText={!compact} />
		</a>
	</div>

	<div class="flex-1 overflow-x-hidden overflow-y-auto px-2 pb-4">
		{#each groups as group (group.id)}
			<div class="mt-4 first:mt-1">
				{#if !compact}
					<p
						class="mb-1 px-3 text-[10.5px] font-semibold tracking-[0.08em] text-subtle uppercase"
						transition:fade={{ duration: 120 }}
					>
						{group.label}
					</p>
				{:else}
					<div class="mx-3 mb-2 h-px bg-line" aria-hidden="true"></div>
				{/if}
				<ul class="space-y-0.5">
					{#each group.items as item (item.href)}
						{@const active = isActive(item.href)}
						<li>
							<a
								href={item.href}
								onclick={onnavigate}
								aria-current={active ? 'page' : undefined}
								title={compact ? item.label : undefined}
								class="group relative flex h-8 items-center gap-3 rounded-md px-3 text-[13px] font-medium transition-colors duration-[var(--d-fast)]
									{compact ? 'justify-center px-0' : ''}
									{active ? 'text-fg' : 'text-muted hover:bg-surface-2/70 hover:text-fg'}"
							>
								{#if active}
									<span
										class="absolute inset-0 rounded-md border border-line bg-surface-2 shadow-e1"
										in:receive={{ key: 'nav-active' }}
										out:send={{ key: 'nav-active' }}
										aria-hidden="true"
									>
										<span class="absolute top-1.5 bottom-1.5 left-0 w-[3px] rounded-r bg-accent"
										></span>
									</span>
								{/if}
								<item.icon
									class="relative size-4 shrink-0 transition-colors {active
										? 'text-accent'
										: 'text-subtle group-hover:text-muted'}"
									strokeWidth={1.75}
								/>
								{#if !compact}
									<span class="relative truncate">{item.label}</span>
									{#if item.shortcut}
										<kbd
											class="relative ml-auto opacity-0 transition-opacity group-hover:opacity-100"
											aria-hidden="true">G {item.shortcut.toUpperCase()}</kbd
										>
									{/if}
								{/if}
							</a>
						</li>
					{/each}
				</ul>
			</div>
		{/each}
	</div>

	{#if !mobile}
		<div class="shrink-0 border-t border-line p-2">
			<button
				type="button"
				onclick={() => (collapsed = !collapsed)}
				class="flex h-8 w-full items-center gap-3 rounded-md px-3 text-[13px] text-muted hover:bg-surface-2 hover:text-fg {compact
					? 'justify-center px-0'
					: ''}"
				aria-label={collapsed ? 'Déplier la barre latérale' : 'Replier la barre latérale'}
			>
				{#if collapsed}
					<PanelLeftOpen class="size-4" strokeWidth={1.75} />
				{:else}
					<PanelLeftClose class="size-4" strokeWidth={1.75} />
					<span>Replier</span>
					<kbd class="ml-auto">[</kbd>
				{/if}
			</button>
		</div>
	{/if}
</nav>

// web/src/components/shell/sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

import { cn } from "@/lib/utils";
import { activeModule } from "@/navigation";

import { useShell } from "./shell-context";

/**
 * Barre latérale desktop : 6 entrées au plus, icône + libellé. Rail de 96 px (libellé sous l'icône) entre 768 et
 * 1280 px, 232 px au-delà. L'entrée active porte un trait accent à gauche.
 */
export function Sidebar() {
  const { modules } = useShell();
  const pathname = usePathname();
  const active = activeModule(pathname, modules);

  return (
    <nav
      aria-label="Navigation principale"
      className="sticky top-0 hidden h-dvh w-24 shrink-0 flex-col border-r border-border bg-surface md:flex xl:w-58"
    >
      <Link
        href="/"
        className="flex h-14 items-center justify-center gap-2 border-b border-border px-4 xl:justify-start"
      >
        <span aria-hidden className="size-2.5 bg-accent" />
        <span className="display text-h3 tracking-wider">CSM</span>
      </Link>
      <ul className="flex flex-1 flex-col gap-1 p-2">
        {modules.map((m) => {
          const isActive = active?.id === m.id;
          const Icon = m.icon;
          return (
            <li key={m.id}>
              <Link
                href={m.href}
                aria-current={isActive ? "page" : undefined}
                className={cn(
                  "relative flex flex-col items-center gap-1 px-1 py-2 text-small text-fg-muted transition-colors hover:bg-surface-2 hover:text-fg xl:h-10 xl:flex-row xl:gap-3 xl:px-3 xl:py-0 xl:text-body",
                  isActive && "bg-surface-2 text-fg",
                )}
              >
                <span
                  aria-hidden
                  className={cn(
                    "absolute top-1 bottom-1 left-0 w-0.5",
                    isActive ? "bg-accent" : "bg-transparent",
                  )}
                />
                <Icon className={cn("size-5 xl:size-4", isActive && "text-accent")} aria-hidden />
                <span className="text-center leading-tight">{m.label}</span>
              </Link>
            </li>
          );
        })}
      </ul>
      <p className="hidden px-4 py-3 font-mono text-small text-fg-muted xl:block">
        Client Solutions
      </p>
    </nav>
  );
}
