// web/src/components/shell/topbar.tsx
"use client";

import * as Menu from "@radix-ui/react-dropdown-menu";
import { Plus, Search } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";

import { Button } from "@/components/ui/button";
import { Kbd } from "@/components/ui/misc";
import { activeModule, activeTab } from "@/navigation";

import { useShell } from "./shell-context";
import { NotificationBell } from "./notification-bell";
import { UserMenu } from "./user-menu";

/**
 * Barre du haut. Desktop : fil (module › onglet), recherche ⌘K, « + Nouveau », menu utilisateur.
 * Mobile : 48 px collante, marque + module courant, recherche, menu utilisateur.
 */
export function Topbar() {
  const { modules, actions, setPaletteOpen } = useShell();
  const pathname = usePathname();
  const mod = activeModule(pathname, modules);
  const tab = mod ? activeTab(pathname, mod) : undefined;

  return (
    <header
      data-print="hide"
      className="sticky top-0 z-30 flex h-12 shrink-0 items-center gap-2 border-b border-border bg-[color-mix(in_oklab,var(--bg)_88%,transparent)] px-3 backdrop-blur md:h-14 md:px-6"
    >
      <Link href="/" className="flex items-center gap-2 md:hidden" aria-label="Accueil CSM">
        <span aria-hidden className="size-2 bg-accent" />
        <span className="display text-body-lg tracking-wider">CSM</span>
      </Link>
      <p className="label-mono min-w-0 truncate text-fg-muted">
        <span className="md:hidden"> · {mod?.label}</span>
        <span className="hidden md:inline">
          {mod?.label}
          {tab && mod?.tabs.length ? ` › ${tab.label}` : ""}
        </span>
      </p>
      <div className="ml-auto flex items-center gap-1 md:gap-2">
        <Button
          variant="ghost"
          className="hidden w-64 justify-start border border-border text-fg-muted md:inline-flex"
          onClick={() => setPaletteOpen(true)}
        >
          <Search /> Rechercher, aller à…
          <span className="ml-auto flex gap-1">
            <Kbd>Ctrl</Kbd>
            <Kbd>K</Kbd>
          </span>
        </Button>
        <Button
          size="icon"
          variant="ghost"
          className="md:hidden"
          aria-label="Rechercher"
          onClick={() => setPaletteOpen(true)}
        >
          <Search className="size-5" />
        </Button>
        {actions.length > 0 ? (
          <Menu.Root>
            <Menu.Trigger asChild>
              <Button variant="secondary" className="hidden md:inline-flex">
                <Plus /> Nouveau
              </Button>
            </Menu.Trigger>
            <Menu.Portal>
              <Menu.Content
                align="end"
                sideOffset={6}
                className="z-50 w-60 border border-border-strong bg-surface py-1 data-[state=open]:animate-fade-in"
              >
                {actions.map((a) => (
                  <Menu.Item
                    key={a.href}
                    asChild
                    className="flex h-control cursor-pointer items-center gap-3 px-3 text-body outline-none data-[highlighted]:bg-surface-2"
                  >
                    <Link href={a.href}>
                      <a.icon className="size-4 text-fg-muted" aria-hidden /> {a.label}
                    </Link>
                  </Menu.Item>
                ))}
              </Menu.Content>
            </Menu.Portal>
          </Menu.Root>
        ) : null}
        <NotificationBell />
        <UserMenu />
      </div>
    </header>
  );
}

// src/lib/components/shell/Topbar.svelte
<script>
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { DropdownMenu } from 'bits-ui';
	import { Menu, Search, Plus, ChevronRight } from 'lucide-svelte';
	import { findNavItem, QUICK_CREATE, isVisible } from '$lib/navigation';
	import ThemeMenu from './ThemeMenu.svelte';
	import NotificationsMenu from './NotificationsMenu.svelte';
	import UserMenu from './UserMenu.svelte';

	/**
	 * @type {{
	 *   user: { id: string, email?: string } | null,
	 *   profile: any,
	 *   onmenu: () => void,
	 *   onsearch: () => void,
	 *   onshortcuts: () => void
	 * }}
	 */
	let { user, profile, onmenu, onsearch, onshortcuts } = $props();

	const current = $derived(findNavItem(page.url.pathname));
	const creations = $derived(QUICK_CREATE.filter((c) => isVisible(c, profile)));
	const isMac = typeof navigator !== 'undefined' && /Mac|iPhone|iPad/.test(navigator.platform);
</script>

<header
	class="sticky top-0 z-40 flex h-[var(--topbar-h)] shrink-0 items-center gap-2 border-b border-line bg-canvas/75 px-3 backdrop-blur-xl sm:px-4"
	data-print="hide"
>
	<button type="button" class="csm-icon-btn md:hidden" onclick={onmenu} aria-label="Ouvrir le menu">
		<Menu class="size-5" strokeWidth={1.75} />
	</button>

	<nav aria-label="Fil d’Ariane" class="min-w-0 flex-1">
		<ol class="flex items-center gap-1.5 text-[13px]">
			{#if current}
				<li class="hidden text-subtle sm:block">{current.group.label}</li>
				<li class="hidden text-subtle sm:block" aria-hidden="true">
					<ChevronRight class="size-3.5" />
				</li>
				<li class="truncate font-medium text-fg" aria-current="page">{current.item.label}</li>
			{:else}
				<li class="truncate font-medium text-fg">{page.data?.title ?? ''}</li>
			{/if}
		</ol>
	</nav>

	<button
		type="button"
		onclick={onsearch}
		class="group hidden h-8 w-64 items-center gap-2 rounded-md border border-line bg-surface/60 px-2.5 text-[13px] text-subtle transition-colors hover:border-line-strong hover:text-muted sm:flex lg:w-80"
	>
		<Search class="size-4" strokeWidth={1.75} />
		<span class="flex-1 text-left">Rechercher…</span>
		<kbd>{isMac ? '⌘' : 'Ctrl'} K</kbd>
	</button>
	<button type="button" class="csm-icon-btn sm:hidden" onclick={onsearch} aria-label="Rechercher">
		<Search class="size-[18px]" strokeWidth={1.75} />
	</button>

	{#if creations.length}
		<DropdownMenu.Root>
			<DropdownMenu.Trigger
				class="flex h-8 items-center gap-1.5 rounded-md bg-accent px-2.5 text-[13px] font-medium text-accent-fg shadow-e1 transition-[filter,transform] hover:brightness-110 active:scale-[0.98]"
			>
				<Plus class="size-4" strokeWidth={2} />
				<span class="hidden sm:inline">Nouveau</span>
			</DropdownMenu.Trigger>
			<DropdownMenu.Portal>
				<DropdownMenu.Content
					sideOffset={8}
					align="end"
					class="csm-pop z-[80] w-60 rounded-lg border border-line bg-surface p-1.5 shadow-e3"
				>
					{#each creations as c (c.href)}
						<DropdownMenu.Item class="csm-menu-item" onSelect={() => goto(c.href)}>
							<c.icon class="size-4 text-subtle" strokeWidth={1.75} />
							{c.label}
						</DropdownMenu.Item>
					{/each}
				</DropdownMenu.Content>
			</DropdownMenu.Portal>
		</DropdownMenu.Root>
	{/if}

	<div class="flex items-center gap-0.5">
		<span class="hidden sm:contents"><ThemeMenu userId={user?.id} /></span>
		{#if user}<NotificationsMenu userId={user.id} />{/if}
	</div>
	<div class="mx-1 h-6 w-px bg-line" aria-hidden="true"></div>
	<UserMenu {profile} email={user?.email} {onshortcuts} />
</header>
